# Generated by Django 5.2.1 on 2025-05-14 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_contactmessage_is_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='is_read',
        ),
    ]
