# Generated by Django 5.2.1 on 2025-05-15 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contactmessage_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='admin_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='publish_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterUniqueTogether(
            name='booking',
            unique_together={('email', 'booking_date')},
        ),
    ]
