# Generated by Django 5.2.1 on 2025-05-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_booking_service'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.AddField(
            model_name='about',
            name='chairman_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/chairman/'),
        ),
        migrations.AddField(
            model_name='about',
            name='chairman_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='md_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/md/'),
        ),
        migrations.AddField(
            model_name='about',
            name='md_message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
