# Generated by Django 5.2.1 on 2025-05-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_delete_story_delete_teammember_about_chairman_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Our Company', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization_logos/')),
                ('address', models.TextField()),
                ('phone1', models.CharField(max_length=20, verbose_name='Phone 1')),
                ('phone2', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone 2')),
                ('email1', models.EmailField(max_length=254, verbose_name='Email 1')),
                ('email2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email 2')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
