# Generated by Django 5.2.1 on 2025-05-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_organizationinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='chairman_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='md_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='about',
            name='chairman_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='about',
            name='md_image',
            field=models.ImageField(blank=True, null=True, upload_to='about/'),
        ),
    ]
