# Generated by Django 5.2.1 on 2025-05-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_about_chairman_name_about_md_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarouselItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='carousel_images/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url_services', models.URLField()),
                ('url_contact', models.URLField()),
            ],
        ),
    ]
