# Generated by Django 5.2.1 on 2025-05-19 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_carouselitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carouselitem',
            name='url_contact',
        ),
        migrations.RemoveField(
            model_name='carouselitem',
            name='url_services',
        ),
    ]
